version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16 #postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - gym-health-tech

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - gym-health-tech

volumes:
  pg_data:
  redis-data:
networks:
  gym-health-tech:
    driver: bridge
