version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16 #postgres:${POSTGRES_VERSION}
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_SUPERUSER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Ho_Chi_Minh"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_SUPERUSER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - gym-health-tech

  redis:
    image: redis:7-alpine
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - gym-health-tech

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - gym-health-tech

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - gym-health-tech

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki/index:/loki/index
      - ./loki/cache:/loki/cache
      - ./loki/chunks:/loki/chunks
      - ./loki/compactor:/loki/compactor
      - ./src/main/resources/loki-config.yml:/etc/loki/local-config.yml:ro
      - ./loki/wal:/wal

    networks:
      - gym-health-tech

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./src/main/resources/promtail-config.yml:/etc/promtail/config.yml
      - ./logs:/logs
    command: -config.file=/etc/promtail/config.yml
    networks:
      - gym-health-tech

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - gym-health-tech

volumes:
  pg_data:
  redis-data:
  rabbitmq_data:
  grafana-storage:
  loki-data:
networks:
  gym-health-tech:
    driver: bridge
