version: '3.8'
services:
  backend:
    container_name: backend
    image: tnydevdocs/gymhealthtech:latest
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    networks:
      - gym-health-tech
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  grafana-agent:
    image: grafana/agent:latest
    container_name: grafana-agent
    volumes:
      - ./grafana-agent.yml:/etc/agent/grafana-agent.yml:ro
      - ./logs:/logs
    command: --config.file=/etc/agent/grafana-agent.yml
    restart: always
    networks:
      - gym-health-tech

networks:
  gym-health-tech:
    driver: bridge
