spring:
  datasource:
    url: ${POSTGRES_URL_DEV}
    username: ${APP_DB_USER_DEV}
    password: ${APP_DB_PASSWORD_DEV}
  rabbitmq:
    host: ${RABBITMQ_HOST_DEV}
    port: ${RABBITMQ_PORT_DEV}
    username: ${RABBITMQ_USERNAME_DEV}
    password: ${RABBITMQ_PASSWORD_DEV}
    virtual-host: ${RABBITMQ_VHOST_DEV}
  data:
    redis:
      host: redis
      port: 6379
