server:
  port: ${PORT:8080}
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: gym-health-tech
  profiles:
    active: ${APP_PROFILE:dev}
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5432}/${POSTGRES_DB:gymhealthtech}
    username: ${APP_DB_USER:postgres}
    password: ${APP_DB_PASSWORD:root}
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 15
      minimum-idle: 3
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:thientri.trank17@gmail.com}
    password: ${MAIL_PASSWORD:spgs mysu ghqy clqv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com.thentrees.gymhealthtech: DEBUG
    org.springframework: WARN # giảm noise từ Spring
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

app:
  prefix: ${APP_PREFIX:/api/v1}
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}
  jwt:
    secret: ${JWT_SECRET:RjU5u3hN1YwqW7sPgRyd8g1qHj2W9U8QqGtxbYnTjFI=}
    expiration: ${JWT_EXPIRATION:3600000} # 1 hour
  verification:
    email:
      expiration: ${EMAIL_VERIFICATION_EXPIRATION:86400000} # 24 hours

aws:
  s3:
    bucket: ${S3_BUCKET_NAME:gym-health-tech-app}
    s3AccessKey: ${S3_ACCESS_KEY_ID:AKIAXW35EKKSJUUZ5N3Q}
    s3SecretKey: ${S3_SECRET_ACCESS_KEY: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}
    region: ${S3_REGION:ap-southeast-1}
