spring:
  datasource:
    url: ${POSTGRES_URL_PROD}
    username: ${APP_DB_USER_PROD}
    password: ${APP_DB_PASSWORD_PROD}
  rabbitmq:
    host: ${RABBITMQ_HOST_PROD}
    port: ${RABBITMQ_PORT_PROD}
    username: ${RABBITMQ_USERNAME_PROD}
    password: ${RABBITMQ_PASSWORD_PROD}
    virtual-host: ${RABBITMQ_VHOST_PROD}
  data:
    redis:
      host: ${REDIS_HOST_PROD}
      port: ${REDIS_PORT_PROD}
      username: default
      password: ${REDIS_PASSWORD_PROD:}
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms
