server:
  port: ${PORT:8080}
spring:
  main:
    register-shutdown-hook: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: gym-health-tech
  datasource:
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 15
      minimum-idle: 3
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com.thentrees.gymhealthtech: DEBUG
    org.springframework: WARN # giảm noise từ Spring
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

app:
  prefix: ${APP_PREFIX:/api/v1}
  frontend:
    url: ${FRONTEND_URL}
  jwt:
    secret: ${JWT_SECRET:RjU5u3hN1YwqW7sPgRyd8g1qHj2W9U8QqGtxbYnTjFI=}
    expiration: ${JWT_EXPIRATION:3600000} # 1 hour
  verification:
    email:
      expiration: ${EMAIL_VERIFICATION_EXPIRATION:86400000} # 24 hours

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    s3AccessKey: ${S3_ACCESS_KEY_ID}
    s3SecretKey: ${S3_SECRET_ACCESS_KEY}
    region: ${S3_REGION}

management:
  metrics:
    enable:
      system: false
      process: false
      jvm: false
