name: CI/CD to EC2

on:
  push:
    branches:
      - main  # Chạy CI/CD khi đẩy code lên nhánh main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub dùng máy ảo Ubuntu để chạy CI

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        # Lấy code từ repo GitHub về máy ảo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Thiết lập môi trường build Docker tiên tiến (có caching, cross-platform...)

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Đăng nhập vào DockerHub để có quyền push image

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            tnydevdocs/gymhealthtech:latest
            tnydevdocs/gymhealthtech:${{ github.sha }}

        # Build image từ source và push lên Docker Hub

      - name: Deploy to EC2 via Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/gym-health-tech
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            docker image prune -f

# có thể automation cả các file nhu .env.prod, grafana-agent.yml lên EC2 nếu cần thiết
# Kết nối SSH vào EC2 và chạy lệnh deploy Docker Compose
